# Generated by Django 4.2.6 on 2023-11-08 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="precription",
            name="medicine",
        ),
        migrations.CreateModel(
            name="PrecriptionMedicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="db.medicine"
                    ),
                ),
                (
                    "precription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="db.precription"
                    ),
                ),
            ],
        ),
    ]
