# Generated by Django 4.2.6 on 2023-11-09 08:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0002_remove_precription_medicine_precriptionmedicine"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hospital",
            old_name="adress",
            new_name="address",
        ),
    ]
