# Generated by Django 4.2.6 on 2023-11-17 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0002_rename_precriptionmedicine_prescriptionmedicine_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounting",
            name="patient",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="db.patient"
            ),
        ),
    ]
