# Generated by Django 4.2.6 on 2023-11-09 08:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0004_alter_room_department"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient",
            old_name="adress",
            new_name="address",
        ),
    ]
