# Generated by Django 4.2.6 on 2023-11-09 08:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0005_rename_adress_patient_address"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Precription",
            new_name="Prescription",
        ),
    ]
