# Generated by Django 4.2.6 on 2023-11-09 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0006_rename_precription_prescription"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="room",
        ),
        migrations.AddField(
            model_name="room",
            name="patient",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="db.patient"
            ),
        ),
    ]
