I can help you create some data for your Django models. Here is the code you can use in the Django shell:

# Create a hospital
h = Hospital(name="Lat Yao Hospital", address="Lat Yao, Bangkok, Thailand", phone_number="021234567")
h.save()

# Create two departments
d1 = Department(hospital=h, name="Cardiology")
d1.save()
d2 = Department(hospital=h, name="Neurology")
d2.save()

# Create three roles
r1 = Role(name="Doctor")
r1.save()
r2 = Role(name="Nurse")
r2.save()
r3 = Role(name="Receptionist")
r3.save()

# Create three staff per department
s1 = Staff(name="Dr. Somchai", role=r1, department=d1)
s1.save()
s2 = Staff(name="Nurse Suda", role=r2, department=d1)
s2.save()
s3 = Staff(name="Receptionist Nattaya", role=r3, department=d1)
s3.save()
s4 = Staff(name="Dr. Somsak", role=r1, department=d2)
s4.save()
s5 = Staff(name="Nurse Supaporn", role=r2, department=d2)
s5.save()
s6 = Staff(name="Receptionist Natthaphon", role=r3, department=d2)
s6.save()

# Create three empty rooms per department
r1 = Room(department=d1, room_number=101)
r1.save()
r2 = Room(department=d1, room_number=102)
r2.save()
r3 = Room(department=d1, room_number=103)
r3.save()
r4 = Room(department=d2, room_number=201)
r4.save()
r5 = Room(department=d2, room_number=202)
r5.save()
r6 = Room(department=d2, room_number=203)
r6.save()

# Create 10 patients with 2 that is in room
p1 = Patient(name="Anan", address="Bang Kapi, Bangkok, Thailand", phone_number="0812345678", department=d1, staff=s1, age=45, room=r1)
p1.save()
p2 = Patient(name="Boon", address="Bang Na, Bangkok, Thailand", phone_number="0823456789", department=d1, staff=s1, age=50, room=r2)
p2.save()
p3 = Patient(name="Chai", address="Chatuchak, Bangkok, Thailand", phone_number="0834567890", department=d1, staff=s1, age=55, room=None)
p3.save()
p4 = Patient(name="Dao", address="Din Daeng, Bangkok, Thailand", phone_number="0845678901", department=d1, staff=s2, age=60, room=None)
p4.save()
p5 = Patient(name="Eak", address="Ekkamai, Bangkok, Thailand", phone_number="0856789012", department=d1, staff=s2, age=65, room=None)
p5.save()
p6 = Patient(name="Fah", address="Fang Nua, Bangkok, Thailand", phone_number="0867890123", department=d2, staff=s4, age=40, room=r4)
p6.save()
p7 = Patient(name="Gai", address="Gang Koi, Bangkok, Thailand", phone_number="0878901234", department=d2, staff=s4, age=35, room=r5)
p7.save()
p8 = Patient(name="Hong", address="Huai Khwang, Bangkok, Thailand", phone_number="0889012345", department=d2, staff=s4, age=30, room=None)
p8.save()
p9 = Patient(name="In", address="Inthamara, Bangkok, Thailand", phone_number="0890123456", department=d2, staff=s5, age=25, room=None)
p9.save()
p10 = Patient(name="Jai", address="Jatujak, Bangkok, Thailand", phone_number="0901234567", department=d2, staff=s5, age=20, room=None)
p10.save()

# Create 10 accounting that date today to back 1 year
from datetime import datetime, timedelta
a1 = Accounting(balance=1000.0, date=datetime.now(), hospital=h, patient=p1)
a1.save()
a2 = Accounting(balance=2000.0, date=datetime.now() - timedelta(days=30), hospital=h, patient=p2)
a2.save()
a3 = Accounting(balance=3000.0, date=datetime.now() - timedelta(days=60), hospital=h, patient=p3)
a3.save()
a4 = Accounting(balance=4000.0, date=datetime.now() - timedelta(days=90), hospital=h, patient=p4)
a4.save()
a5 = Accounting(balance=5000.0, date=datetime.now() - timedelta(days=120), hospital=h, patient=p5)
a5.save()
a6 = Accounting(balance=6000.0, date=datetime.now() - timedelta(days=150), hospital=h, patient=p6)
a6.save()
a7 = Accounting(balance=7000.0, date=datetime.now() - timedelta(days=180), hospital=h, patient=p7)
a7.save()
a8 = Accounting(balance=8000.0, date=datetime.now() - timedelta(days=210), hospital=h, patient=p8)
a8.save()
a9 = Accounting(balance=9000.0, date=datetime.now() - timedelta(days=240), hospital=h, patient=p9)
a9.save()
a10 = Accounting(balance=10000.0, date=datetime.now() - timedelta(days=270), hospital=h, patient=p10)
a10.save()

# Create 5 appointments
ap1 = Appointment(staff=s1, patient=p1, dateTime=datetime.now() + timedelta(days=1), detail="Follow-up check")
ap1.save()
ap2 = Appointment(staff=s1, patient=p2, dateTime=datetime.now() + timedelta(days=2), detail="Follow-up check")
ap2.save()
ap3 = Appointment(staff=s4, patient=p6, dateTime=datetime.now() + timedelta(days=3), detail="Follow-up check")
ap3.save()
ap4 = Appointment(staff=s4, patient=p7, dateTime=datetime.now() + timedelta(days=4), detail="Follow-up check")
ap4.save()
ap5 = Appointment(staff=s4, patient=p8, dateTime=datetime.now() + timedelta(days=5), detail="Follow-up check")
ap5.save()

# Create 20 medicines with real medicine name
m1 = Medicine(name="Paracetamol", price=10.0, amount=100)
m1.save()
m2 = Medicine(name="Ibuprofen", price=15.0, amount=100)
m2.save()
m3 = Medicine(name="Aspirin", price=20.0, amount=100)
m3.save()
m4 = Medicine(name="Amoxicillin", price=25.0, amount=100)
m4.save()
m5 = Medicine(name="Ciprofloxacin", price=30.0, amount=100)
m5.save()
m6 = Medicine(name="Metformin", price=35.0, amount=100)
m6.save()
m7 = Medicine(name="Atorvastatin", price=40.0, amount=100)
m7.save()
m8 = Medicine(name="Lisinopril", price=45.0, amount=100)
m8.save()
m9 = Medicine(name="Levothyroxine", price=50.0, amount=100)
m9.save()
m10 = Medicine(name="Omeprazole", price=55.0, amount=100)
m10.save()
m11 = Medicine(name="Amlodipine", price=60.0, amount=100)
m11.save()
m12 = Medicine(name="Metoprolol", price=65.0, amount=100)
m12.save()
m13 = Medicine(name="Losartan", price=70.0, amount=100)
m13.save()
m