I can help you create some data for your Django models. Here is the code you can use in the Django shell:

# Create a hospital
h = Hospital(name="Lat Yao Hospital", address="Lat Yao, Bangkok, Thailand", phone_number="021234567")
h.save()

# Create two departments
d1 = Department(hospital=h, name="Cardiology")
d1.save()
d2 = Department(hospital=h, name="Neurology")
d2.save()

# Create three staff per department
s1 = Staff(name="Dr. Somchai", role=Role.objects.get(name="Doctor"), department=d1)
s1.save()
s2 = Staff(name="Nurse Nong", role=Role.objects.get(name="Nurse"), department=d1)
s2.save()
s3 = Staff(name="Pharmacist Ploy", role=Role.objects.get(name="Pharmacist"), department=d1)
s3.save()
s4 = Staff(name="Dr. Somsak", role=Role.objects.get(name="Doctor"), department=d2)
s4.save()
s5 = Staff(name="Nurse Noi", role=Role.objects.get(name="Nurse"), department=d2)
s5.save()
s6 = Staff(name="Pharmacist Pim", role=Role.objects.get(name="Pharmacist"), department=d2)
s6.save()

# Create three empty rooms per department
r1 = Room(department=d1, room_number=101)
r1.save()
r2 = Room(department=d1, room_number=102)
r2.save()
r3 = Room(department=d1, room_number=103)
r3.save()
r4 = Room(department=d2, room_number=201)
r4.save()
r5 = Room(department=d2, room_number=202)
r5.save()
r6 = Room(department=d2, room_number=203)
r6.save()

# Create 10 patients with 2 that are in rooms
p1 = Patient(name="Arun", address="Bang Kapi, Bangkok, Thailand", phone_number="0812345678", department=d1, staff=s1, age=45, room=r1)
p1.save()
p2 = Patient(name="Boon", address="Bang Na, Bangkok, Thailand", phone_number="0823456789", department=d1, staff=s1, age=50, room=r2)
p2.save()
p3 = Patient(name="Chai", address="Chatuchak, Bangkok, Thailand", phone_number="0834567890", department=d1, staff=s1, age=55, room=None)
p3.save()
p4 = Patient(name="Dao", address="Din Daeng, Bangkok, Thailand", phone_number="0845678901", department=d1, staff=s2, age=60, room=None)
p4.save()
p5 = Patient(name="Eak", address="Ekkamai, Bangkok, Thailand", phone_number="0856789012", department=d1, staff=s2, age=65, room=None)
p5.save()
p6 = Patient(name="Fah", address="Lat Phrao, Bangkok, Thailand", phone_number="0867890123", department=d2, staff=s4, age=40, room=r4)
p6.save()
p7 = Patient(name="Gai", address="Ladprao, Bangkok, Thailand", phone_number="0878901234", department=d2, staff=s4, age=35, room=r5)
p7.save()
p8 = Patient(name="Hong", address="Huai Khwang, Bangkok, Thailand", phone_number="0889012345", department=d2, staff=s4, age=30, room=None)
p8.save()
p9 = Patient(name="In", address="Ratchathewi, Bangkok, Thailand", phone_number="0890123456", department=d2, staff=s5, age=25, room=None)
p9.save()
p10 = Patient(name="Jai", address="Sathon, Bangkok, Thailand", phone_number="0901234567", department=d2, staff=s5, age=20, room=None)
p10.save()

# Create 10 accounting records that date from today to back 1 year
from datetime import datetime, timedelta
a1 = Accounting(balance=1000, date=datetime.now(), hospital=h, patient=p1)
a1.save()
a2 = Accounting(balance=2000, date=datetime.now() - timedelta(days=30), hospital=h, patient=p2)
a2.save()
a3 = Accounting(balance=3000, date=datetime.now() - timedelta(days=60), hospital=h, patient=p3)
a3.save()
a4 = Accounting(balance=4000, date=datetime.now() - timedelta(days=90), hospital=h, patient=p4)
a4.save()
a5 = Accounting(balance=5000, date=datetime.now() - timedelta(days=120), hospital=h, patient=p5)
a5.save()
a6 = Accounting(balance=6000, date=datetime.now() - timedelta(days=150), hospital=h, patient=p6)
a6.save()
a7 = Accounting(balance=7000, date=datetime.now() - timedelta(days=180), hospital=h, patient=p7)
a7.save()
a8 = Accounting(balance=8000, date=datetime.now() - timedelta(days=210), hospital=h, patient=p8)
a8.save()
a9 = Accounting(balance=9000, date=datetime.now() - timedelta(days=240), hospital=h, patient=p9)
a9.save()
a10 = Accounting(balance=10000, date=datetime.now() - timedelta(days=270), hospital=h, patient=p10)
a10.save()

# Create 5 appointments
ap1 = Appointment(staff=s1, patient=p1, dateTime=datetime.now() + timedelta(days=1), detail="Follow-up checkup")
ap1.save()
ap2 = Appointment(staff=s1, patient=p2, dateTime=datetime.now() + timedelta(days=2), detail="Follow-up checkup")
ap2.save()
ap3 = Appointment(staff=s4, patient=p6, dateTime=datetime.now() + timedelta(days=3), detail="Follow-up checkup")
ap3.save()
ap4 = Appointment(staff=s4, patient=p7, dateTime=datetime.now() + timedelta(days=4), detail="Follow-up checkup")
ap4.save()
ap5 = Appointment(staff=s4, patient=p8, dateTime=datetime.now() + timedelta(days=5), detail="Follow-up checkup")
ap5.save()

# Create 20 medicines with real medicine names
m1 = Medicine(name="Paracetamol", price=10, amount=100)
m1.save()
m2 = Medicine(name="Ibuprofen", price=20, amount=100)
m2.save()
m3 = Medicine(name="Aspirin", price=30, amount=100)
m3.save()
m4 = Medicine(name="Amoxicillin", price=40, amount=100)
m4.save()
m5 = Medicine(name="Ciprofloxacin", price=50, amount=100)
m5.save()
m6 = Medicine(name="Metronidazole", price=60, amount=100)
m6.save()
m7 = Medicine(name="Omeprazole", price=70, amount=100)
m7.save()
m8 = Medicine(name="Lansoprazole", price=80, amount=100)
m8.save()
m9 = Medicine(name="Simvastatin", price=90, amount=100)
m9.save()
m10 = Medicine(name="Atorvastatin", price=100, amount=100)
m10.save()
m11 = Medicine(name="Metformin", price=110, amount=100)
m11.save()
m12 = Medicine(name="Gliclazide", price=120, amount=100)
m12.save()
m13 = Medicine(name="Amlodipine", price=130, amount=100)
m13.save()
m14 = Medicine(name="Losartan", price=140, amount=100)
m14.save()
m15 = Medicine(name="Bisoprolol", price=150, amount=100)
m15.save()
m16 = Medicine(name="Salbutamol", price=160, amount=100)
m16.save()
m17 = Medicine(name="Prednisolone", price=170, amount=100)
m17.save()
m18 = Medicine(name="Levothyroxine", price=180, amount=100)
m18.save()
m19 = Medicine(name="Warfarin", price=190, amount=100)
m19.save()
m20 = Medicine(name="Clopidogrel", price=200, amount=100)
m20.save()

# Create 3 diseases with real disease names
d1 = Disease(name="Hypertension")
d1.save()
d2 = Disease(name="Diabetes")
d2.save()
d3 = Disease(name="Asthma")
d3.save()

# Create 3 treatments with real treatment names
t1 = Treatment(name="Lifestyle modification")
t1.save()
t2 = Treatment(name="Insulin injection")
t2.save()
t3 = Treatment(name="Inhaler therapy")
t3.save()

# Create 10 prescriptions
pr1 = Prescription(staff=s1, patient=p1)
pr1.save()
pr2 = Prescription(staff=s1, patient=p2)
pr2.save()
pr3 = Prescription(staff=s1, patient=p3)
pr3.save()
pr4 = Prescription(staff=s2, patient=p4)
pr4.save()
pr5 = Prescription(staff=s2, patient=p5)
pr5.save()
pr6 = Prescription(staff=s4, patient=p